template: '@acyort/pigeon'
description: To experience, to experiment, to explore, to expand, to be expert...

plugins:
  - hook.js
  - '@acyort/pigeon'

repository: 2EXP/2exp.github.io

favicon: favicon.png

public: public

timezone: Asia/Shanghai

menu:
  archives: /archives/
  tags: /tags/
  about: /about/

perpage: 5

title: 2EXP
