name: Auto Update Blog

on:
  issues
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Checkout Blog Config Branch
      uses: actions/checkout@v2
      with:
        ref: blog-config
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install acyort -g
        npm install
    - name: Add Worktree to Branch master
      run: |
        git worktree add public master
    - name: Regenerate Public Static Data
      run: |
        acyort flow
    - name: Copy Assets to Public Folder
      run: |
        cp ./favicon.png ./public/favicon.png
        cp ./README.md   ./public/README.md
    - name: Commit Static Data
      run: |
        git config user.name "Automata"
        git config user.email "Automata@email.com"
        cd public
        git add --all
        git commit -m "Updated by github actions workflow auto-update.yml - `date +'%Y-%m-%d %H:%M:%S'`"
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add - <<< "${{ secrets.BLOG_DEPLOY_KEY }}"
    - name: Push Changes
      run: |
        git push -q origin master
